"""
Verifier Agent -- reasoning-check on compliance-diff output, not a re-judgment.

This agent is Phase 5 in the pipeline. It reads compliance_findings (populated
by agents/compliance_diff.py) and checks whether each verdict is internally
consistent with the evidence that was shown to the compliance-diff agent: the
full statutory text and the matched lease clause.

What "verify" means precisely
-------------------------------
The verifier does NOT independently re-derive a compliance verdict from scratch.
That would just be a second diff agent making a second judgment call, which adds
cost and latency without adding a meaningful check. Instead, given the actual
statutory full_text and the actual matched lease clause_text side by side, it
checks whether the compliance-diff agent's stated status and explanation
genuinely follow from comparing those two texts. This is a narrower, more
mechanical reasoning-check: is the stated conclusion consistent with the stated
evidence? It does not require the verifier to know the law independently.

Why a different model family is required
-----------------------------------------
Using the same model to verify its own output would not catch correlated
reasoning errors -- systematic blind spots and failure modes shared across
calls to the same model. This agent deliberately uses gpt-4o-mini via LiteLLM
rather than Claude (used by agents/lease_parser.py and
agents/compliance_diff.py), so that a judgment error in the compliance-diff
step has a meaningful chance of being caught rather than being repeated. This
architectural decision is logged in docs/decisions.md.

This file must never import the anthropic SDK. Any change that adds an anthropic
import here defeats the purpose of having a separate verifier model.

Why 'absent' findings are excluded
------------------------------------
compliance_findings rows with status='absent' are generated by a deterministic,
rule-based path in compliance_diff.py with no LLM judgment behind them: if
lease_clauses shows no matching clause, the status is absent, period. There is
no LLM reasoning to check for consistency. Only LLM-judged statuses
('compliant', 'contradicts', 'needs_review') are sent to this agent.

LiteLLM tool-calling shape (differs from Anthropic SDK used elsewhere)
------------------------------------------------------------------------
LiteLLM uses the OpenAI function-calling wrapper shape, not Anthropic's shape:

  tools = [{"type": "function", "function": {"name": ..., "parameters": ...}}]
  tool_choice = {"type": "function", "function": {"name": ...}}

Results are at response.choices[0].message.tool_calls (a list, possibly None).
Each call's arguments are a raw JSON STRING at tool_calls[0].function.arguments
that must be json.loads()'d explicitly. This is structurally different from
Anthropic's tool_block.input (a pre-parsed dict). json.loads() failures are
treated as batch failures, same as any other error.
"""

import json
import sys
from typing import Any

import litellm

from api.config import settings
from api.db import get_connection

# Smaller than the other two agents' _BATCH_SIZE=25. Each row here carries
# three pieces of text (full_text, clause_text, and the original explanation),
# so batches need to stay a manageable prompt size.
_BATCH_SIZE = 15


# ---------------------------------------------------------------------------
# Types
# ---------------------------------------------------------------------------

FindingRow = dict[str, Any]      # one row from the join query in get_findings_to_verify
Verification = dict[str, Any]    # one validated entry from the LLM response


# ---------------------------------------------------------------------------
# Tool definition (OpenAI function-calling shape, not Anthropic shape)
# ---------------------------------------------------------------------------

_RECORD_VERIFICATIONS_TOOL: list[dict[str, Any]] = [
    {
        "type": "function",
        "function": {
            "name": "record_verifications",
            "description": (
                "Record whether each compliance finding's stated status and "
                "explanation genuinely follow from comparing the statutory text "
                "to the lease clause. This is a consistency check on the "
                "compliance-diff agent's reasoning, not an independent legal "
                "judgment from scratch."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "verifications": {
                        "type": "array",
                        "description": "One entry per requirement_key supplied in the prompt.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "requirement_key": {
                                    "type": "string",
                                    "description": "Exactly as supplied in the prompt.",
                                },
                                "confirmed": {
                                    "type": "boolean",
                                    "description": (
                                        "confirmed=true means: the compliance-diff "
                                        "agent's STATED VERDICT is well-supported by "
                                        "ITS OWN STATED REASONING when you compare the "
                                        "statutory text to the lease clause -- i.e., if "
                                        "you were a supervisor checking this agent's "
                                        "work, you would sign off that its conclusion "
                                        "logically follows from the comparison it was "
                                        "asked to make. A 'contradicts' or 'needs_review' "
                                        "verdict about a real legal problem in the lease "
                                        "should be confirmed=true if the reasoning that "
                                        "led to it was sound. "
                                        "confirmed=false means specifically: the "
                                        "compliance-diff agent's own conclusion does NOT "
                                        "follow from its own stated comparison -- e.g. "
                                        "it said 'compliant' but the clause actually "
                                        "conflicts with the statute, or it said "
                                        "'contradicts' but the lease clause it quoted "
                                        "does not actually support that reading, or its "
                                        "explanation does not logically connect to the "
                                        "verdict it chose. Do NOT set confirmed=false "
                                        "merely because the underlying finding describes "
                                        "a real legal problem in the lease."
                                    ),
                                },
                                "note": {
                                    "type": "string",
                                    "description": (
                                        "Required in both cases. Write directly for a "
                                        "landlord reading a compliance report -- not as "
                                        "internal audit commentary. Never mention 'the "
                                        "agent', 'compliance-diff', or any pipeline "
                                        "component. Never quote the status label as a "
                                        "technical term; describe the situation in plain "
                                        "language instead. Never narrate your reasoning "
                                        "process ('the reasoning points to', 'the "
                                        "conclusion should reflect'). "
                                        "If confirmed=true: one or two sentences on the "
                                        "substance -- what the law requires, what the "
                                        "lease says, and why that reading holds. "
                                        "If confirmed=false: explain the actual legal "
                                        "conflict or gap in plain language, as a direct "
                                        "second opinion -- what the law requires, what "
                                        "the lease actually does, and why this is a "
                                        "problem worth noting."
                                    ),
                                },
                            },
                            "required": ["requirement_key", "confirmed", "note"],
                        },
                    }
                },
                "required": ["verifications"],
            },
        },
    }
]

_TOOL_CHOICE: dict[str, Any] = {
    "type": "function",
    "function": {"name": "record_verifications"},
}


# ---------------------------------------------------------------------------
# Database helpers
# ---------------------------------------------------------------------------

def get_findings_to_verify(conn, lease_id: str) -> list[FindingRow]:
    """Query compliance findings that have LLM-judged statuses for this lease.

    Joins compliance_findings to legal_sources (for full_text and citation) and
    to lease_clauses (for clause_text). Only rows with status IN ('compliant',
    'contradicts', 'needs_review') are returned -- 'absent' rows are excluded
    because they carry no LLM reasoning to check.

    Parameters
    ----------
    conn:
        An open psycopg connection obtained via ``get_connection()``.
    lease_id:
        UUID string of the lease whose findings are to be verified.

    Returns
    -------
    list[FindingRow]
        Each dict contains ``requirement_key``, ``citation``, ``full_text``,
        ``clause_text``, ``status``, and ``explanation``.
    """
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT
                cf.requirement_key,
                ls.citation,
                ls.full_text,
                lc.clause_text,
                cf.status,
                cf.explanation
            FROM compliance_findings cf
            JOIN legal_sources ls
                ON ls.requirement_key = cf.requirement_key
            JOIN lease_clauses lc
                ON lc.requirement_key = cf.requirement_key
                AND lc.lease_id = cf.lease_id
            WHERE cf.lease_id = %(lease_id)s
              AND cf.status IN ('compliant', 'contradicts', 'needs_review')
            ORDER BY cf.requirement_key
            """,
            {"lease_id": lease_id},
        )
        rows = cur.fetchall()
        columns = [desc[0] for desc in cur.description]

    return [dict(zip(columns, row)) for row in rows]


def _reset_verifier_fields(conn, lease_id: str) -> None:
    """Set verifier_confirmed and verifier_note to NULL for all findings in this lease.

    Called before writing new verification results. If compliance_diff was rerun
    and a requirement_key's status changed, a stale verifier_note from a prior
    status must not linger and appear to apply to the new verdict.

    Parameters
    ----------
    conn:
        An open psycopg connection with ``autocommit=True``.
    lease_id:
        UUID string identifying the lease being re-verified.
    """
    with conn.cursor() as cur:
        cur.execute(
            """
            UPDATE compliance_findings
            SET verifier_confirmed = NULL,
                verifier_note = NULL
            WHERE lease_id = %s
            """,
            (lease_id,),
        )


def _update_verifier_fields(
    conn,
    lease_id: str,
    verifications: list[Verification],
) -> None:
    """Write verifier_confirmed and verifier_note back to compliance_findings.

    Only rows that passed validation in ``classify_verification`` are updated.
    Rows that failed API calls or validation remain at NULL (set by
    ``_reset_verifier_fields``), which is the correct signal that verification
    was attempted but did not produce a usable result.

    Parameters
    ----------
    conn:
        An open psycopg connection with ``autocommit=True``.
    lease_id:
        UUID string identifying the lease.
    verifications:
        Validated entries from ``classify_verification``, each containing
        ``requirement_key``, ``confirmed``, and ``note``.
    """
    if not verifications:
        return

    with conn.cursor() as cur:
        cur.executemany(
            """
            UPDATE compliance_findings
            SET verifier_confirmed = %s,
                verifier_note = %s
            WHERE lease_id = %s
              AND requirement_key = %s
            """,
            [
                (v["confirmed"], v["note"], lease_id, v["requirement_key"])
                for v in verifications
            ],
        )


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def _validate_verification(
    entry: Any,
    expected_keys: set[str],
    batch_label: str,
) -> Verification | None:
    """Validate one verification entry returned by gpt-4o-mini.

    Checks in order:
      1. Must be a dict.
      2. ``requirement_key`` must be a non-empty string.
      3. ``requirement_key`` must be in ``expected_keys`` (hallucination guard --
         same pattern as lease_parser.py and compliance_diff.py).
      4. ``confirmed`` must be a boolean.
      5. ``note`` must be a non-empty, non-whitespace-only string.

    Parameters
    ----------
    entry:
        Raw object from the parsed verifications array.
    expected_keys:
        Requirement keys sent to this specific batch.
    batch_label:
        Short string like ``"batch 2/4"`` used in warning messages.

    Returns
    -------
    Verification or None
        The validated entry, or None if it must be skipped.
    """
    if not isinstance(entry, dict):
        print(f"  [WARN] {batch_label}: skipping non-dict verification entry: {entry!r}")
        return None

    key = entry.get("requirement_key")
    confirmed = entry.get("confirmed")
    note = entry.get("note")

    if not isinstance(key, str) or not key:
        print(
            f"  [WARN] {batch_label}: skipping entry with missing/invalid "
            f"requirement_key: {entry!r}"
        )
        return None

    if key not in expected_keys:
        print(
            f"  [WARN] {batch_label}: skipping '{key}' -- not in the set of "
            "requirement_keys sent to the model for this batch "
            "(hallucinated or mistyped key)."
        )
        return None

    if not isinstance(confirmed, bool):
        print(
            f"  [WARN] {batch_label}: skipping '{key}' -- 'confirmed' must be "
            f"boolean, got {confirmed!r}"
        )
        return None

    if not isinstance(note, str) or not note.strip():
        print(
            f"  [WARN] {batch_label}: skipping '{key}' -- 'note' is missing, "
            "non-string, or whitespace-only."
        )
        return None

    return {
        "requirement_key": key,
        "confirmed": confirmed,
        "note": note,
    }


# ---------------------------------------------------------------------------
# LLM verification
# ---------------------------------------------------------------------------

def classify_verification(rows_to_verify: list[FindingRow]) -> list[Verification]:
    """Check compliance findings for internal consistency using gpt-4o-mini.

    Each batch prompt presents the statutory text, the matched lease clause, and
    the compliance-diff agent's stated verdict side by side, framed as a
    reasoning-consistency check rather than an independent legal judgment. The
    model is asked whether the stated conclusion genuinely follows from comparing
    the two texts, not whether it would have reached the same conclusion itself.

    On any failure (API exception, missing/empty tool_calls, JSON parse failure),
    the affected requirement_keys are logged by name and their
    verifier_confirmed/verifier_note remain NULL in the database (already reset
    by ``_reset_verifier_fields``). Failures do not raise -- other batches
    continue.

    Parameters
    ----------
    rows_to_verify:
        Rows from ``get_findings_to_verify``. Each must contain
        ``requirement_key``, ``citation``, ``full_text``, ``clause_text``,
        ``status``, and ``explanation``.

    Returns
    -------
    list[Verification]
        Validated verification entries. Keys that failed or were omitted by the
        model are not included -- their database rows remain at NULL, which is
        the correct representation of "attempted but unresolved."
    """
    all_keys = [row["requirement_key"] for row in rows_to_verify]
    rows_by_key = {row["requirement_key"]: row for row in rows_to_verify}

    batches = [
        all_keys[i : i + _BATCH_SIZE] for i in range(0, len(all_keys), _BATCH_SIZE)
    ]
    total_batches = len(batches)
    all_results: list[Verification] = []

    for batch_idx, batch_keys in enumerate(batches, start=1):
        batch_label = f"batch {batch_idx}/{total_batches}"
        expected_keys = set(batch_keys)

        sections: list[str] = []
        for key in batch_keys:
            row = rows_by_key[key]
            sections.append(
                f"REQUIREMENT: {key}\n"
                f"Citation: {row['citation']}\n"
                f"Full statutory text:\n{row['full_text']}\n\n"
                f"Matched lease clause:\n{row['clause_text']}\n\n"
                f"Compliance-diff verdict: {row['status']}\n"
                f"Compliance-diff explanation: {row['explanation']}"
            )

        prompt = (
            "You are checking the reasoning of an automated compliance review tool.\n\n"
            "For each REQUIREMENT below, you are given:\n"
            "  1. The full statutory text of the legal requirement\n"
            "  2. The matched clause from the lease\n"
            "  3. The compliance-diff agent's verdict (compliant / contradicts / "
            "needs_review) and its explanation\n\n"
            "Your task: check whether the compliance-diff agent's STATED VERDICT is "
            "well-supported by ITS OWN STATED REASONING when you compare the "
            "statutory text to the lease clause. Think of yourself as a supervisor "
            "checking this agent's work: would you sign off that its conclusion "
            "logically follows from the comparison it was asked to make?\n\n"
            "CRITICAL DISTINCTION -- read this carefully:\n"
            "confirmed=true means: the agent's reasoning process was sound, given "
            "the two texts. This says nothing about whether the underlying lease has "
            "a legal problem. A 'contradicts' verdict about a real legal problem "
            "should be confirmed=true if the reasoning that led to it was correct.\n"
            "confirmed=false means specifically: the agent's OWN CONCLUSION does NOT "
            "follow from its OWN STATED COMPARISON -- for example, it said 'compliant' "
            "but its own explanation describes a conflict; or it said 'contradicts' "
            "but the clause it quoted does not actually conflict with the statute; or "
            "its explanation does not logically connect to the verdict it chose.\n"
            "Do NOT set confirmed=false merely because the underlying finding "
            "describes a real legal problem in the lease. A correctly-reasoned "
            "'contradicts' or 'needs_review' about a genuine issue should be "
            "confirmed=true.\n\n"
            "Concrete example:\n"
            "  - The diff agent says 'contradicts' and correctly explains that the "
            "lease clause conflicts with the statute on late fees. That is "
            "confirmed=true, even though it means the lease has a problem.\n"
            "  - The diff agent says 'compliant' but its own explanation actually "
            "describes a conflict between the clause and the statute. That is "
            "confirmed=false, because the agent's own reasoning undermines its "
            "own verdict.\n\n"
            "In your note: write as if speaking directly to the landlord -- no "
            "references to 'the agent', 'compliance-diff', or any internal "
            "component. Do not quote the status label as a technical term; "
            "describe what is happening in plain language. Do not narrate your "
            "reasoning process; state the substantive legal point directly. "
            "If confirmed=true: briefly confirm what the law requires and why the "
            "lease's handling of it holds up. "
            "If confirmed=false: explain the actual legal conflict or gap in the "
            "landlord's own terms -- what the law requires, what the lease "
            "actually says or does, and why it matters.\n\n"
            + "\n\n---\n\n".join(sections)
            + "\n\nCall record_verifications with one entry per REQUIREMENT listed above."
        )

        print(f"  [{batch_label}] Verifying {len(batch_keys)} findings ...")

        try:
            response = litellm.completion(
                model="gpt-4o-mini",
                max_tokens=4096,
                tools=_RECORD_VERIFICATIONS_TOOL,
                tool_choice=_TOOL_CHOICE,
                messages=[{"role": "user", "content": prompt}],
            )
        except Exception as exc:
            failed_keys_str = ", ".join(sorted(batch_keys))
            print(
                f"  [ERROR] {batch_label}: LiteLLM completion failed -- {exc}\n"
                f"  Failed requirement_keys: {failed_keys_str}"
            )
            # Verifier fields remain NULL (already reset). Do not append
            # placeholder entries here -- NULL is the correct representation
            # of "attempted but unresolved" for this agent.
            continue

        # Extract tool_calls from the OpenAI-shaped response.
        tool_calls = None
        try:
            tool_calls = response.choices[0].message.tool_calls
        except (AttributeError, IndexError):
            pass

        if not tool_calls:
            failed_keys_str = ", ".join(sorted(batch_keys))
            print(
                f"  [ERROR] {batch_label}: no tool_calls in response.\n"
                f"  Failed requirement_keys: {failed_keys_str}"
            )
            continue

        # Arguments are a raw JSON string -- must be parsed explicitly.
        try:
            arguments = json.loads(tool_calls[0].function.arguments)
        except (json.JSONDecodeError, AttributeError, IndexError) as exc:
            failed_keys_str = ", ".join(sorted(batch_keys))
            print(
                f"  [ERROR] {batch_label}: failed to parse tool_calls arguments "
                f"as JSON -- {exc}\n"
                f"  Failed requirement_keys: {failed_keys_str}"
            )
            continue

        raw_entries: list[Any] = arguments.get("verifications", [])

        validated: list[Verification] = []
        for entry in raw_entries:
            result = _validate_verification(entry, expected_keys, batch_label)
            if result is not None:
                validated.append(result)

        # Warn about keys the model omitted.
        returned_keys = {v["requirement_key"] for v in validated}
        missing_keys = expected_keys - returned_keys
        if missing_keys:
            print(
                f"  [WARN] {batch_label}: model did not return verifications for: "
                + ", ".join(sorted(missing_keys))
            )

        all_results.extend(validated)

    return all_results


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def run_verifier(lease_id: str) -> None:
    """Run verification on all LLM-judged compliance findings for a lease.

    Reads compliance_findings (populated by agents/compliance_diff.py) and
    checks each verdict for internal consistency against the statutory text and
    lease clause using gpt-4o-mini. Writes results back to verifier_confirmed
    and verifier_note. Idempotent: verifier fields are reset to NULL before any
    new results are written.

    Parameters
    ----------
    lease_id:
        UUID string of a lease that has already been processed by
        agents/compliance_diff.py.

    Raises
    ------
    RuntimeError
        If settings.openai_api_key is not set, raised immediately rather than
        letting every batch fail with a less obvious error.
    """
    if not settings.openai_api_key:
        raise RuntimeError(
            "settings.openai_api_key is not set. "
            "Set the OPENAI_API_KEY environment variable (or add it to .env) "
            "before running the verifier."
        )

    # LiteLLM reads the key from the environment; set it from settings so the
    # rest of the codebase's single source of truth (api/config.py) is respected.
    import os
    os.environ["OPENAI_API_KEY"] = settings.openai_api_key

    print(f"Running verifier for lease {lease_id} ...")

    conn = get_connection()

    try:
        rows = get_findings_to_verify(conn, lease_id)

        if not rows:
            print(
                "No LLM-judged findings to verify for this lease "
                "(all findings may be 'absent', or compliance_diff has not been run yet)."
            )
            return

        print(f"Found {len(rows)} findings to verify.")

        # Reset verifier fields before writing new results so stale notes from
        # a prior compliance_diff run cannot appear to apply to a new verdict.
        _reset_verifier_fields(conn, lease_id)

        print(f"\nRunning verification in batches of {_BATCH_SIZE} ...")
        verifications = classify_verification(rows)

        _update_verifier_fields(conn, lease_id, verifications)

        # Build summary.
        total_sent = len(rows)
        total_verified = len(verifications)
        failed_count = total_sent - total_verified

        confirmed_entries = [v for v in verifications if v["confirmed"]]
        disputed_entries = [v for v in verifications if not v["confirmed"]]

        # Collect keys that were sent but got no validated result back.
        verified_keys = {v["requirement_key"] for v in verifications}
        all_sent_keys = {row["requirement_key"] for row in rows}
        failed_keys = sorted(all_sent_keys - verified_keys)

        print(f"\n{'=' * 60}")
        print(f"Verifier summary for lease {lease_id}:")
        print(f"  Total findings sent for verification: {total_sent}")
        print(f"  Successfully verified:                {total_verified}")
        print(f"  Confirmed (reasoning holds):          {len(confirmed_entries)}")
        print(f"  Not confirmed (disagreements):        {len(disputed_entries)}")
        if disputed_entries:
            print("  Disputed findings (most actionable):")
            for v in sorted(disputed_entries, key=lambda x: x["requirement_key"]):
                print(f"    {v['requirement_key']}: {v['note']}")
        if failed_count:
            print(f"  Failed to verify (API/parse error):  {failed_count}")
            if failed_keys:
                print(f"    Failed keys: {', '.join(failed_keys)}")
        print(f"{'=' * 60}")

    finally:
        conn.close()


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python agents/verifier.py <lease_id>")
        sys.exit(1)

    run_verifier(sys.argv[1])
